name       : python-bottleneck
version    : 1.2.1
release    : 1
source     :
    - https://github.com/kwgoodman/bottleneck/archive/v1.2.1.tar.gz : 268a21f451f1fe3749619c64d36e9feda84fefdcb82a4701a3e63a9430874b22
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - Python-2.0
    - ZPL-2.0
component  : programming.python
summary    : Fast NumPy array functions written in C.
description: |
    Fast NumPy array functions written in C.
builddeps  :
    - pkgconfig(python-3.5)
    - numpy
    - python-setuptools
rundeps    :
    - numpy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
