name       : python-bottleneck
version    : 1.3.7
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/B/Bottleneck/Bottleneck-1.3.7.tar.gz : e1467e373ad469da340ed0ff283214d6531cc08bfdca2083361a3aa6470681f8
homepage   : https://github.com/pydata/bottleneck
license    : BSD-2-Clause
component  : programming.python
summary    : Fast NumPy array functions written in C
description: |
    Bottleneck is a collection of fast, NaN-aware NumPy array functions written in C.
builddeps  :
    - pkgconfig(python3)
    - numpy
    - python-pytest     # check
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -vv --color=yes --pyargs bottleneck
