name       : python-bottleneck
version    : 1.3.2
release    : 6
source     :
    - https://github.com/pydata/bottleneck/archive/v1.3.2.tar.gz : 5efac98f689c445eecc95400fb53d7bbc92435fa6db7a3dc75b427641d757807
homepage   : https://github.com/pydata/bottleneck
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - Python-2.0
    - ZPL-2.0
component  : programming.python
summary    : Fast NumPy array functions written in C.
description: |
    Bottleneck is a collection of fast, NaN-aware NumPy array functions written in C.
builddeps  :
    - pkgconfig(python3)
    - numpy
    - python-pytest
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
