name       : python-bottleneck
version    : 1.3.4
release    : 8
source     :
    - https://github.com/pydata/bottleneck/archive/refs/tags/v1.3.4.tar.gz : f33f5c7bfa922911d4439ff332e5f9a1863587aefdb38b159802e3356293284d
homepage   : https://github.com/pydata/bottleneck
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - Python-2.0
    - ZPL-2.0
component  : programming.python
summary    : Fast NumPy array functions written in C
description: |
    Bottleneck is a collection of fast, NaN-aware NumPy array functions written in C.
builddeps  :
    - pkgconfig(python3)
    - numpy
    - python-hypothesis # check
    - python-pytest
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
