name       : python-bottleneck
version    : 1.3.4
release    : 7
source     :
    - https://github.com/pydata/bottleneck/archive/v1.3.4.tar.gz : 368bc8c86204299221dbf3a402bfa2a1b4dad53fbacb067ade13f7b32167fcf7
homepage   : https://github.com/pydata/bottleneck
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - Python-2.0
    - ZPL-2.0
component  : programming.python
summary    : Fast NumPy array functions written in C
description: |
    Bottleneck is a collection of fast, NaN-aware NumPy array functions written in C.
builddeps  :
    - pkgconfig(python3)
    - numpy
    - python-hypothesis # check
    - python-pytest
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
